import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import FooterPage from "./components/FooterPage";
import WorkoutLibrary from "./workout-library/page";
import WorkProvider from "@/context/WorkContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-oswald', // Define the custom CSS variable
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" 
      className={`${geistSans.variable} ${oswald.variable}  ${geistMono.variable} h-full antialiased`} 
    >
      <body className="min-h-full flex flex-col">
        <WorkProvider>

        <Navbar></Navbar>
        
        {children}
        <FooterPage></FooterPage>
        <ToastContainer />
        </WorkProvider>

      </body>
    </html>
  );
}
